// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjcyrtpeuhlzubsehgyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqY3lydHBldWhsenVic2VoZ3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTUyNTEsImV4cCI6MjA3NzMzMTI1MX0.U0gBwoPp3e89pc5PxKUI0JVD6F6_D2UI15KlvexWII0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});